theme: league
title: DevOps intro
revealjs_config:
  dependencies:
  - src: 'plugin/menu/menu.js'
  history: true
  parallaxBackgroundImage: 'images/index-background.jpg'
  parallaxBackgroundSize: '3000px 2120px'
  menu:
    side: left
    titleSelector: 'h1'
    hideMissingTitles: true
    themes: false
    openButton: true
