VAGRANTFILE_API_VERSION = '2'.freeze
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.hostname = 'web-server'

  if Vagrant.has_plugin?('vagrant-omnibus')
    config.omnibus.chef_version = '12.8.1'
  end

  config.vm.box = 'bento/ubuntu-16.04'

  config.vm.network :private_network, ip: '33.33.36.10'

  config.berkshelf.enabled = true

  config.vm.provision :chef_solo do |chef|
    chef.version = '12.8.1'
    chef.run_list = [
      'recipe[apt]',
      'recipe[web-server]'
    ]
  end
end
